### ISSUE TITLE
Bug:cannot pickle 'weakref' object

### ISSUE THREAD

**Issue by zhuhui-in** [shuyana/DiffusionProteinLigand#3]
Dear authors, 
i was trying to reproduce the example you provided below:
```
python generate.py \
    --ckpt_path "checkpoints/DPL_v1.ckpt" \
    --output_dir "workdir/generate/example_DPL" \
    --protein "LSEQLKHCNGILKELLSKKHAAYAWPFYKPVDASALGLHDYHDIIKHPMDLSTVKRKMENRDYRDAQEFAADVRLMFSNCYKYNPPDHDVVAMARKLQDVFEFRYAKMPD" \
    --ligand "Cc1ccc2c(c1c3cc(cc4c3nc([nH]4)C5CC5)c6c(noc6C)C)cccn2" \
    --num_samples 8
```
however there are some problems
```
Global seed set to 1234
Total number of atoms: 140
Using cache found in /pubhome/hzhu02/.cache/torch/hub/facebookresearch_esm_main
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "/pubhome/hzhu02/models/DiffusionProteinLigand/generate.py", line 170, in <module>
    main(args)
  File "/pubhome/hzhu02/models/DiffusionProteinLigand/generate.py", line 110, in main
    positions = trainer.predict(
  File "/pubhome/hzhu02/miniconda3/envs/dpl/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 949, in predict
    return self._call_and_handle_interrupt(
  File "/pubhome/hzhu02/miniconda3/envs/dpl/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/pubhome/hzhu02/miniconda3/envs/dpl/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 107, in launch
    mp.start_processes(
  File "/pubhome/hzhu02/miniconda3/envs/dpl/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
    process.start()
  File "/pubhome/hzhu02/miniconda3/envs/dpl/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/pubhome/hzhu02/miniconda3/envs/dpl/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/pubhome/hzhu02/miniconda3/envs/dpl/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/pubhome/hzhu02/miniconda3/envs/dpl/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/pubhome/hzhu02/miniconda3/envs/dpl/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/pubhome/hzhu02/miniconda3/envs/dpl/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref' object
```
would you help me fix it?

env:
the same as the environment in environment.yml
pytorch-lightning         1.7.7 
python                    3.9.16 
pytorch                   1.12.1  
cudatoolkit               11.3.1

**Comment by shuyana** [comment]
Dear zhuhui-in,

Thank you for reporting the error. While I did not encounter the error on my machine, I was able to reproduce it by specifying `strategy='ddp_spawn'` when instantiating the trainer. Therefore, it is possible that the 'ddp_spawn' strategy was used implicitly in your case, leading to the error.

Could you please try to specify the trainer strategy explicitly? You can do this by adding the following line of code:

```python
trainer = pl.Trainer.from_argparse_args(
    args,
    accelerator="auto",
    strategy="ddp",  # <- Added: specify the trainer strategy explicitly
    default_root_dir=args.output_dir,
    max_epochs=-1,
)
```

Please let me know if this solves the problem or not.

Best regards,

Shuya Nakata

**Comment by shuyana** [comment]
Closing due to no response. Please reopen if necessary.

**Comment by shuyana** [comment]
Closing due to no response. Please reopen if necessary.
